from PyQt5 import QtCore, QtGui, QtWidgets

def fillTab2():
    analysisTab = QtWidgets.QWidget()
    analysisTab.setObjectName("analysisTab")
    gridLayoutWidget = QtWidgets.QWidget(analysisTab)
    gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 96))
    gridLayoutWidget.setObjectName("gridLayoutWidget")
    gridLayout = QtWidgets.QGridLayout(gridLayoutWidget)
    gridLayout.setContentsMargins(0, 0, 0, 0)
    gridLayout.setObjectName("gridLayout")
    label = QtWidgets.QLabel(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
    label.setSizePolicy(sizePolicy)
    label.setObjectName("label")
    gridLayout.addWidget(label, 0, 0, 1, 1, QtCore.Qt.AlignRight)
    label_2 = QtWidgets.QLabel(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(label_2.sizePolicy().hasHeightForWidth())
    label_2.setSizePolicy(sizePolicy)
    label_2.setObjectName("label_2")
    gridLayout.addWidget(label_2, 1, 0, 1, 1, QtCore.Qt.AlignRight)
    pushButton_2 = QtWidgets.QPushButton(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(pushButton_2.sizePolicy().hasHeightForWidth())
    pushButton_2.setSizePolicy(sizePolicy)
    pushButton_2.setObjectName("pushButton_2")
    gridLayout.addWidget(pushButton_2, 1, 3, 1, 1, QtCore.Qt.AlignLeft)
    pushButton_3 = QtWidgets.QPushButton(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(pushButton_3.sizePolicy().hasHeightForWidth())
    pushButton_3.setSizePolicy(sizePolicy)
    pushButton_3.setObjectName("pushButton_3")
    gridLayout.addWidget(pushButton_3, 1, 4, 1, 1, QtCore.Qt.AlignLeft)
    label_3 = QtWidgets.QLabel(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(label_3.sizePolicy().hasHeightForWidth())
    label_3.setSizePolicy(sizePolicy)
    label_3.setObjectName("label_3")
    gridLayout.addWidget(label_3, 2, 0, 1, 1, QtCore.Qt.AlignRight)
    label_4 = QtWidgets.QLabel(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(label_4.sizePolicy().hasHeightForWidth())
    label_4.setSizePolicy(sizePolicy)
    label_4.setObjectName("label_4")
    gridLayout.addWidget(label_4, 1, 2, 1, 1, QtCore.Qt.AlignRight)
    pushButton = QtWidgets.QPushButton(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(pushButton.sizePolicy().hasHeightForWidth())
    pushButton.setSizePolicy(sizePolicy)
    pushButton.setObjectName("pushButton")
    gridLayout.addWidget(pushButton, 1, 1, 1, 1, QtCore.Qt.AlignVCenter)
    comboBox = QtWidgets.QComboBox(gridLayoutWidget)
    comboBox.setObjectName("comboBox")
    gridLayout.addWidget(comboBox, 2, 1, 1, 2)
    comboBox_2 = QtWidgets.QComboBox(gridLayoutWidget)
    comboBox_2.setObjectName("comboBox_2")
    gridLayout.addWidget(comboBox_2, 0, 1, 1, 2)
    groupBox = QtWidgets.QGroupBox(analysisTab)
    groupBox.setGeometry(QtCore.QRect(10, 100, 151, 421))
    groupBox.setObjectName("groupBox")
    verticalLayoutWidget = QtWidgets.QWidget(groupBox)
    verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 153, 371))
    verticalLayoutWidget.setObjectName("verticalLayoutWidget")
    verticalLayout = QtWidgets.QVBoxLayout(verticalLayoutWidget)
    verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
    verticalLayout.setContentsMargins(0, 0, 0, 0)
    verticalLayout.setSpacing(0)
    verticalLayout.setObjectName("verticalLayout")
    checkBox_3 = QtWidgets.QCheckBox(verticalLayoutWidget)
    checkBox_3.setObjectName("checkBox_3")
    verticalLayout.addWidget(checkBox_3)
    checkBox_2 = QtWidgets.QCheckBox(verticalLayoutWidget)
    checkBox_2.setObjectName("checkBox_2")
    verticalLayout.addWidget(checkBox_2)
    checkBox = QtWidgets.QCheckBox(verticalLayoutWidget)
    checkBox.setObjectName("checkBox")
    verticalLayout.addWidget(checkBox)
    checkBox_4 = QtWidgets.QCheckBox(verticalLayoutWidget)
    checkBox_4.setObjectName("checkBox_4")
    verticalLayout.addWidget(checkBox_4)
    textEdit = QtWidgets.QTextEdit(groupBox)
    textEdit.setGeometry(QtCore.QRect(0, 20, 121, 31))
    textEdit.setObjectName("textEdit")
    groupBox_2 = QtWidgets.QGroupBox(analysisTab)
    groupBox_2.setGeometry(QtCore.QRect(170, 100, 591, 421))
    groupBox_2.setObjectName("groupBox_2")
    frame = QtWidgets.QFrame(groupBox_2)
    frame.setGeometry(QtCore.QRect(10, 40, 551, 251))
    frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame.setFrameShadow(QtWidgets.QFrame.Raised)
    frame.setObjectName("frame")
    label_5 = QtWidgets.QLabel(frame)
    label_5.setGeometry(QtCore.QRect(160, 100, 221, 61))
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(label_5.sizePolicy().hasHeightForWidth())
    label_5.setSizePolicy(sizePolicy)
    label_5.setMaximumSize(QtCore.QSize(361, 16777215))
    label_5.setObjectName("label_5")
    frame_2 = QtWidgets.QFrame(groupBox_2)
    frame_2.setGeometry(QtCore.QRect(9, 299, 551, 111))
    frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_2.setObjectName("frame_2")
    label_6 = QtWidgets.QLabel(frame_2)
    label_6.setGeometry(QtCore.QRect(166, 50, 211, 20))
    label_6.setObjectName("label_6")
    pushButton_4 = QtWidgets.QPushButton(groupBox_2)
    pushButton_4.setGeometry(QtCore.QRect(560, 40, 21, 31))
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(pushButton_4.sizePolicy().hasHeightForWidth())
    pushButton_4.setSizePolicy(sizePolicy)
    pushButton_4.setMinimumSize(QtCore.QSize(20, 0))
    pushButton_4.setObjectName("pushButton_4")
    pushButton_5 = QtWidgets.QPushButton(analysisTab)
    pushButton_5.setGeometry(QtCore.QRect(760, 120, 21, 31))
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(pushButton_5.sizePolicy().hasHeightForWidth())
    pushButton_5.setSizePolicy(sizePolicy)
    pushButton_5.setMinimumSize(QtCore.QSize(20, 0))
    pushButton_5.setObjectName("pushButton_5")
    pushButton_6 = QtWidgets.QPushButton(analysisTab)
    pushButton_6.setGeometry(QtCore.QRect(760, 150, 21, 31))
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(pushButton_6.sizePolicy().hasHeightForWidth())
    pushButton_6.setSizePolicy(sizePolicy)
    pushButton_6.setMinimumSize(QtCore.QSize(20, 0))
    pushButton_6.setObjectName("pushButton_6")

    _translate = QtCore.QCoreApplication.translate

    label.setText(_translate("MainWindow", "Plugin"))
    label_2.setText(_translate("MainWindow", "Static Analysis"))
    pushButton_2.setText(_translate("MainWindow", "Run"))
    pushButton_3.setText(_translate("MainWindow", "Stop"))
    label_3.setText(_translate("MainWindow", "Point of Interest Type"))
    label_4.setText(_translate("MainWindow", "Dynamic Analysis"))
    pushButton.setText(_translate("MainWindow", "Run"))
    groupBox.setTitle(_translate("MainWindow", "Point of Interest View"))
    checkBox_3.setText(_translate("MainWindow", "Point of Interest A"))
    checkBox_2.setText(_translate("MainWindow", "Point of Interest B"))
    checkBox.setText(_translate("MainWindow", "Point of Interest C"))
    checkBox_4.setText(_translate("MainWindow", "Point of Interest D"))
    groupBox_2.setTitle(_translate("MainWindow", "Detailed Point of Interest View"))
    label_5.setText(_translate("MainWindow", "Points of Interest Content Area"))
    label_6.setText(_translate("MainWindow", "Terminal Window Content Area"))
    pushButton_4.setText(_translate("MainWindow", "C"))
    pushButton_5.setText(_translate("MainWindow", "A"))
    pushButton_6.setText(_translate("MainWindow", "O"))
    
    return analysisTab

