from PyQt5 import QtCore, QtGui, QtWidgets

def fillTab3():
    PluginTab = QtWidgets.QWidget()
    PluginTab.setObjectName("PluginTab")
    horizontalLayout = QtWidgets.QHBoxLayout(PluginTab)
    horizontalLayout.setObjectName("horizontalLayout")
    PluginView = QtWidgets.QFrame(PluginTab)
    PluginView.setFrameShape(QtWidgets.QFrame.WinPanel)
    PluginView.setFrameShadow(QtWidgets.QFrame.Sunken)
    PluginView.setLineWidth(3)
    PluginView.setObjectName("PluginView")
    verticalLayout_2 = QtWidgets.QVBoxLayout(PluginView)
    verticalLayout_2.setObjectName("verticalLayout_2")
    LabelPluginView = QtWidgets.QLabel(PluginView)
    LabelPluginView.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
    LabelPluginView.setObjectName("LabelPluginView")
    verticalLayout_2.addWidget(LabelPluginView)
    PluginSearchBar = QtWidgets.QLineEdit(PluginView)
    PluginSearchBar.setObjectName("PluginSearchBar")
    verticalLayout_2.addWidget(PluginSearchBar)
    PluginList = QtWidgets.QVBoxLayout()
    PluginList.setObjectName("PluginList")
    PluginA = QtWidgets.QLabel(PluginView)
    PluginA.setObjectName("PluginA")
    PluginList.addWidget(PluginA, 0, QtCore.Qt.AlignHCenter)
    PluginB = QtWidgets.QLabel(PluginView)
    PluginB.setObjectName("PluginB")
    PluginList.addWidget(PluginB, 0, QtCore.Qt.AlignHCenter)
    PluginC = QtWidgets.QLabel(PluginView)
    PluginC.setObjectName("PluginC")
    PluginList.addWidget(PluginC, 0, QtCore.Qt.AlignHCenter)
    verticalLayout_2.addLayout(PluginList)
    spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    verticalLayout_2.addItem(spacerItem)
    ButtonPVnewPlugin = QtWidgets.QPushButton(PluginView)
    ButtonPVnewPlugin.setObjectName("ButtonPVnewPlugin")
    verticalLayout_2.addWidget(ButtonPVnewPlugin, 0, QtCore.Qt.AlignRight)
    horizontalLayout.addWidget(PluginView)
    DetailedPluginView = QtWidgets.QFrame(PluginTab)
    DetailedPluginView.setLayoutDirection(QtCore.Qt.LeftToRight)
    DetailedPluginView.setFrameShape(QtWidgets.QFrame.WinPanel)
    DetailedPluginView.setFrameShadow(QtWidgets.QFrame.Sunken)
    DetailedPluginView.setLineWidth(3)
    DetailedPluginView.setObjectName("DetailedPluginView")
    verticalLayout = QtWidgets.QVBoxLayout(DetailedPluginView)
    verticalLayout.setObjectName("verticalLayout")
    LabelDetailedPLuginView = QtWidgets.QLabel(DetailedPluginView)
    LabelDetailedPLuginView.setTextFormat(QtCore.Qt.RichText)
    LabelDetailedPLuginView.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
    LabelDetailedPLuginView.setObjectName("LabelDetailedPLuginView")
    verticalLayout.addWidget(LabelDetailedPLuginView)
    DPVContents = QtWidgets.QFrame(DetailedPluginView)
    DPVContents.setEnabled(True)
    DPVContents.setFrameShape(QtWidgets.QFrame.StyledPanel)
    DPVContents.setFrameShadow(QtWidgets.QFrame.Raised)
    DPVContents.setObjectName("DPVContents")
    horizontalLayout_2 = QtWidgets.QHBoxLayout(DPVContents)
    horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
    horizontalLayout_2.setObjectName("horizontalLayout_2")
    DPVLeft = QtWidgets.QFormLayout()
    DPVLeft.setObjectName("DPVLeft")
    LabelDPVPluginStructure = QtWidgets.QLabel(DPVContents)
    LabelDPVPluginStructure.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    LabelDPVPluginStructure.setObjectName("LabelDPVPluginStructure")
    DPVLeft.setWidget(0, QtWidgets.QFormLayout.LabelRole, LabelDPVPluginStructure)
    DPVPluginStructure = QtWidgets.QLineEdit(DPVContents)
    DPVPluginStructure.setAlignment(QtCore.Qt.AlignCenter)
    DPVPluginStructure.setObjectName("DPVPluginStructure")
    DPVLeft.setWidget(0, QtWidgets.QFormLayout.FieldRole, DPVPluginStructure)
    LabelDPVPluginDataSet = QtWidgets.QLabel(DPVContents)
    LabelDPVPluginDataSet.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    LabelDPVPluginDataSet.setObjectName("LabelDPVPluginDataSet")
    DPVLeft.setWidget(1, QtWidgets.QFormLayout.LabelRole, LabelDPVPluginDataSet)
    DPVPluginDataSet = QtWidgets.QLineEdit(DPVContents)
    DPVPluginDataSet.setAlignment(QtCore.Qt.AlignCenter)
    DPVPluginDataSet.setObjectName("DPVPluginDataSet")
    DPVLeft.setWidget(1, QtWidgets.QFormLayout.FieldRole, DPVPluginDataSet)
    LabelDPVPluginName = QtWidgets.QLabel(DPVContents)
    LabelDPVPluginName.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    LabelDPVPluginName.setObjectName("LabelDPVPluginName")
    DPVLeft.setWidget(2, QtWidgets.QFormLayout.LabelRole, LabelDPVPluginName)
    DPVPluginName = QtWidgets.QLineEdit(DPVContents)
    DPVPluginName.setAlignment(QtCore.Qt.AlignCenter)
    DPVPluginName.setObjectName("DPVPluginName")
    DPVLeft.setWidget(2, QtWidgets.QFormLayout.FieldRole, DPVPluginName)
    LabelDPVPLuginDescription = QtWidgets.QLabel(DPVContents)
    LabelDPVPLuginDescription.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    LabelDPVPLuginDescription.setObjectName("LabelDPVPLuginDescription")
    DPVLeft.setWidget(3, QtWidgets.QFormLayout.LabelRole, LabelDPVPLuginDescription)
    DPVPluginDescription = QtWidgets.QTextEdit(DPVContents)
    DPVPluginDescription.setObjectName("DPVPluginDescription")
    DPVLeft.setWidget(3, QtWidgets.QFormLayout.FieldRole, DPVPluginDescription)
    LabelDPVOutputField = QtWidgets.QLabel(DPVContents)
    LabelDPVOutputField.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    LabelDPVOutputField.setObjectName("LabelDPVOutputField")
    DPVLeft.setWidget(4, QtWidgets.QFormLayout.LabelRole, LabelDPVOutputField)
    DPVDefaultOutputField = QtWidgets.QComboBox(DPVContents)
    DPVDefaultOutputField.setCurrentText("")
    DPVDefaultOutputField.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
    DPVDefaultOutputField.setObjectName("DPVDefaultOutputField")
    DPVLeft.setWidget(4, QtWidgets.QFormLayout.FieldRole, DPVDefaultOutputField)
    LabelDPVPointOfInterest = QtWidgets.QLabel(DPVContents)
    LabelDPVPointOfInterest.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    LabelDPVPointOfInterest.setObjectName("LabelDPVPointOfInterest")
    DPVLeft.setWidget(5, QtWidgets.QFormLayout.LabelRole, LabelDPVPointOfInterest)
    DVPPointOfInterest = QtWidgets.QTextBrowser(DPVContents)
    DVPPointOfInterest.setObjectName("DVPPointOfInterest")
    DPVLeft.setWidget(5, QtWidgets.QFormLayout.FieldRole, DVPPointOfInterest)
    horizontalLayout_2.addLayout(DPVLeft)
    DPVRight = QtWidgets.QVBoxLayout()
    DPVRight.setContentsMargins(-1, -1, -1, 0)
    DPVRight.setObjectName("DPVRight")
    ButtonDPVPluginStructure = QtWidgets.QPushButton(DPVContents)
    ButtonDPVPluginStructure.setObjectName("ButtonDPVPluginStructure")
    DPVRight.addWidget(ButtonDPVPluginStructure, 0, QtCore.Qt.AlignTop)
    ButtonDPVBDataset = QtWidgets.QPushButton(DPVContents)
    ButtonDPVBDataset.setObjectName("ButtonDPVBDataset")
    DPVRight.addWidget(ButtonDPVBDataset)
    spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    DPVRight.addItem(spacerItem1)
    horizontalLayout_2.addLayout(DPVRight)
    verticalLayout.addWidget(DPVContents)
    savingframe = QtWidgets.QHBoxLayout()
    savingframe.setSpacing(0)
    savingframe.setObjectName("savingframe")
    ButtonDeletePlugin = QtWidgets.QPushButton(DetailedPluginView)
    ButtonDeletePlugin.setObjectName("ButtonDeletePlugin")
    savingframe.addWidget(ButtonDeletePlugin)
    spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    savingframe.addItem(spacerItem2)
    ButtonSavePlugin = QtWidgets.QPushButton(DetailedPluginView)
    ButtonSavePlugin.setObjectName("ButtonSavePlugin")
    savingframe.addWidget(ButtonSavePlugin, 0, QtCore.Qt.AlignLeft)
    verticalLayout.addLayout(savingframe)
    horizontalLayout.addWidget(DetailedPluginView)
    horizontalLayout.setStretch(0, 1)
    horizontalLayout.setStretch(1, 3)

    _translate = QtCore.QCoreApplication.translate

    LabelPluginView.setText(_translate("PluginTab", "Plugin View"))
    PluginA.setText(_translate("PluginTab", "Plugin a"))
    PluginB.setText(_translate("PluginTab", "Plugin b"))
    PluginC.setText(_translate("PluginTab", "Plugin c"))
    ButtonPVnewPlugin.setText(_translate("PluginTab", "New"))
    LabelDetailedPLuginView.setText(_translate("PluginTab", "Detailed Plugin View"))
    LabelDPVPluginStructure.setText(_translate("PluginTab", "Plugin Structure"))
    DPVPluginStructure.setText(_translate("PluginTab", "Plugin Structure file path..."))
    LabelDPVPluginDataSet.setText(_translate("PluginTab", "Plugin Predetermined Data Set"))
    DPVPluginDataSet.setText(_translate("PluginTab", "Plugin Predifined Data Set..."))
    LabelDPVPluginName.setText(_translate("PluginTab", "Plugin Name"))
    DPVPluginName.setText(_translate("PluginTab", "Plugin Name..."))
    LabelDPVPLuginDescription.setText(_translate("PluginTab", "Plugin Description"))
    DPVPluginDescription.setHtml(_translate("PluginTab",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Plugin Description...</p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
    LabelDPVOutputField.setText(_translate("PluginTab", "Default Output Field"))
    LabelDPVPointOfInterest.setText(_translate("PluginTab", "Points Of Interest"))
    DVPPointOfInterest.setHtml(_translate("PluginTab",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">List of points of Interest...</p></body></html>"))
    ButtonDPVPluginStructure.setText(_translate("PluginTab", "Browse"))
    ButtonDPVBDataset.setText(_translate("PluginTab", "Browse"))
    ButtonDeletePlugin.setText(_translate("PluginTab", "Delete"))
    ButtonSavePlugin.setText(_translate("PluginTab", "Save"))
    
    return PluginTab