from PyQt5 import QtCore, QtGui, QtWidgets

def fillTab4():
    pointsOfInterestTab = QtWidgets.QWidget()
    pointsOfInterestTab.setObjectName("pointsOfInterestTab")

    frame = QtWidgets.QFrame(pointsOfInterestTab)
    frame.setGeometry(QtCore.QRect(10, 20, 201, 511))
    frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame.setFrameShadow(QtWidgets.QFrame.Raised)
    frame.setObjectName("frame")
    gridLayoutWidget = QtWidgets.QWidget(frame)
    gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 181, 493))
    gridLayoutWidget.setObjectName("gridLayoutWidget")
    gridLayout_5 = QtWidgets.QGridLayout(gridLayoutWidget)
    gridLayout_5.setContentsMargins(0, 0, 0, 0)
    gridLayout_5.setVerticalSpacing(6)
    gridLayout_5.setObjectName("gridLayout_5")
    textEdit = QtWidgets.QTextEdit(gridLayoutWidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(textEdit.sizePolicy().hasHeightForWidth())
    textEdit.setSizePolicy(sizePolicy)
    textEdit.setObjectName("textEdit")
    gridLayout_5.addWidget(textEdit, 1, 0, 1, 1)
    label = QtWidgets.QLabel(gridLayoutWidget)
    label.setObjectName("label")
    gridLayout_5.addWidget(label, 0, 0, 1, 1)
    verticalLayout = QtWidgets.QVBoxLayout()
    verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
    verticalLayout.setObjectName("verticalLayout")
    label_2 = QtWidgets.QLabel(gridLayoutWidget)
    label_2.setObjectName("label_2")
    verticalLayout.addWidget(label_2, 0, QtCore.Qt.AlignHCenter)
    label_3 = QtWidgets.QLabel(gridLayoutWidget)
    label_3.setObjectName("label_3")
    verticalLayout.addWidget(label_3, 0, QtCore.Qt.AlignHCenter)
    label_4 = QtWidgets.QLabel(gridLayoutWidget)
    label_4.setObjectName("label_4")
    verticalLayout.addWidget(label_4, 0, QtCore.Qt.AlignHCenter)
    label_5 = QtWidgets.QLabel(gridLayoutWidget)
    label_5.setObjectName("label_5")
    verticalLayout.addWidget(label_5, 0, QtCore.Qt.AlignHCenter)
    gridLayout_5.addLayout(verticalLayout, 2, 0, 2, 1)
    pushButton = QtWidgets.QPushButton(gridLayoutWidget)
    pushButton.setObjectName("pushButton")
    gridLayout_5.addWidget(pushButton, 4, 0, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)



    frame_2 = QtWidgets.QFrame(pointsOfInterestTab)
    frame_2.setGeometry(QtCore.QRect(219, 19, 551, 511))
    frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_2.setObjectName("frame_2")
    gridLayoutWidget_3 = QtWidgets.QWidget(frame_2)
    gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 531, 481))
    gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
    gridLayout_3 = QtWidgets.QGridLayout(gridLayoutWidget_3)
    gridLayout_3.setContentsMargins(0, 0, 0, 0)
    gridLayout_3.setObjectName("gridLayout_3")
    pushButton_2 = QtWidgets.QPushButton(gridLayoutWidget_3)
    pushButton_2.setObjectName("pushButton_2")
    gridLayout_3.addWidget(pushButton_2, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
    pushButton_3 = QtWidgets.QPushButton(gridLayoutWidget_3)
    pushButton_3.setObjectName("pushButton_3")
    gridLayout_3.addWidget(pushButton_3, 3, 1, 1, 1, QtCore.Qt.AlignRight)
    frame_3 = QtWidgets.QFrame(gridLayoutWidget_3)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(frame_3.sizePolicy().hasHeightForWidth())
    frame_3.setSizePolicy(sizePolicy)
    frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_3.setObjectName("frame_3")
    label_11 = QtWidgets.QLabel(frame_3)
    label_11.setGeometry(QtCore.QRect(160, 180, 211, 17))
    label_11.setObjectName("label_11")
    gridLayout_3.addWidget(frame_3, 2, 0, 1, 2)
    label_6 = QtWidgets.QLabel(gridLayoutWidget_3)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(label_6.sizePolicy().hasHeightForWidth())
    label_6.setSizePolicy(sizePolicy)
    label_6.setAlignment(QtCore.Qt.AlignCenter)
    label_6.setObjectName("label_6")
    gridLayout_3.addWidget(label_6, 0, 0, 1, 2, QtCore.Qt.AlignTop)
    gridLayout_4 = QtWidgets.QGridLayout()
    gridLayout_4.setObjectName("gridLayout_4")
    label_12 = QtWidgets.QLabel(gridLayoutWidget_3)
    label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    label_12.setObjectName("label_12")
    gridLayout_4.addWidget(label_12, 0, 0, 1, 1)
    label_13 = QtWidgets.QLabel(gridLayoutWidget_3)
    label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    label_13.setObjectName("label_13")
    gridLayout_4.addWidget(label_13, 1, 0, 1, 1)
    comboBox = QtWidgets.QComboBox(gridLayoutWidget_3)
    comboBox.setCurrentText("")
    comboBox.setObjectName("comboBox")
    gridLayout_4.addWidget(comboBox, 0, 1, 1, 1)
    comboBox_2 = QtWidgets.QComboBox(gridLayoutWidget_3)
    comboBox_2.setCurrentText("")
    comboBox_2.setObjectName("comboBox_2")
    gridLayout_4.addWidget(comboBox_2, 1, 1, 1, 1)
    gridLayout_3.addLayout(gridLayout_4, 1, 0, 1, 2)

    _translate = QtCore.QCoreApplication.translate

    label.setText(_translate("MainWindow", "Point of Interest View"))
    label_2.setText(_translate("MainWindow", "Point of Interest A"))
    label_3.setText(_translate("MainWindow", "Point of Interest B"))
    label_4.setText(_translate("MainWindow", "Point of Interest C"))
    label_5.setText(_translate("MainWindow", "Point of Interest X"))
    pushButton.setText(_translate("MainWindow", "New"))


    pushButton_2.setText(_translate("MainWindow", "Delete"))
    pushButton_3.setText(_translate("MainWindow", "Save"))
    label_11.setText(_translate("MainWindow", "Point Of Interest Content Area"))
    label_6.setText(_translate("MainWindow", "Detail Point of Interest View"))
    label_12.setText(_translate("MainWindow", "Plugin"))
    label_13.setText(_translate("MainWindow", "Point of Interest Type"))
    
    return pointsOfInterestTab