from PyQt5 import QtCore, QtGui, QtWidgets

def fillTab4():
    pointsOfInterestTab = QtWidgets.QWidget()
    pointsOfInterestTab.setObjectName("pointsOfInterestTab")

    groupBox_3 = QtWidgets.QGroupBox(pointsOfInterestTab)
    groupBox_3.setGeometry(QtCore.QRect(10, 10, 181, 550))
    groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
    groupBox_3.setObjectName("groupBox_3")
    verticalLayoutWidget_2 = QtWidgets.QWidget(groupBox_3)
    verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 161, 471))
    verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
    verticalLayout_2 = QtWidgets.QVBoxLayout(verticalLayoutWidget_2)
    verticalLayout_2.setContentsMargins(0, 0, 0, 0)
    verticalLayout_2.setSpacing(20)
    verticalLayout_2.setObjectName("verticalLayout_2")
    lineEdit = QtWidgets.QLineEdit(verticalLayoutWidget_2)
    lineEdit.setObjectName("lineEdit")
    lineEdit.addAction(QtGui.QIcon("resources/search.png"), QtWidgets.QLineEdit.LeadingPosition)
    verticalLayout_2.addWidget(lineEdit)
    listWidget = QtWidgets.QListWidget(verticalLayoutWidget_2)
    listWidget.setObjectName("listWidget")
    listWidget.addItem("Point of Interest A")
    listWidget.addItem("Point of Interest B")
    listWidget.addItem("Point of Interest C")
    listWidget.addItem("Point of Interest D")
    verticalLayout_2.addWidget(listWidget)
    pushButton_7 = QtWidgets.QPushButton(verticalLayoutWidget_2)
    pushButton_7.setObjectName("pushButton_7")
    verticalLayout_2.addWidget(pushButton_7)



    frame_2 = QtWidgets.QFrame(pointsOfInterestTab)
    frame_2.setGeometry(QtCore.QRect(219, 19, 551, 540))
    frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_2.setObjectName("frame_2")
    gridLayoutWidget_3 = QtWidgets.QWidget(frame_2)
    gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 531, 481))
    gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
    gridLayout_3 = QtWidgets.QGridLayout(gridLayoutWidget_3)
    gridLayout_3.setContentsMargins(0, 0, 0, 0)
    gridLayout_3.setObjectName("gridLayout_3")
    pushButton_2 = QtWidgets.QPushButton(gridLayoutWidget_3)
    pushButton_2.setObjectName("pushButton_2")
    gridLayout_3.addWidget(pushButton_2, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
    pushButton_3 = QtWidgets.QPushButton(gridLayoutWidget_3)
    pushButton_3.setObjectName("pushButton_3")
    gridLayout_3.addWidget(pushButton_3, 3, 1, 1, 1, QtCore.Qt.AlignRight)
    frame_3 = QtWidgets.QFrame(gridLayoutWidget_3)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(frame_3.sizePolicy().hasHeightForWidth())
    frame_3.setSizePolicy(sizePolicy)
    frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_3.setObjectName("frame_3")
    label_11 = QtWidgets.QLabel(frame_3)
    label_11.setGeometry(QtCore.QRect(160, 180, 211, 17))
    label_11.setObjectName("label_11")
    gridLayout_3.addWidget(frame_3, 2, 0, 1, 2)
    label_6 = QtWidgets.QLabel(gridLayoutWidget_3)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(label_6.sizePolicy().hasHeightForWidth())
    label_6.setSizePolicy(sizePolicy)
    label_6.setAlignment(QtCore.Qt.AlignCenter)
    label_6.setObjectName("label_6")
    gridLayout_3.addWidget(label_6, 0, 0, 1, 2, QtCore.Qt.AlignTop)
    gridLayout_4 = QtWidgets.QGridLayout()
    gridLayout_4.setObjectName("gridLayout_4")
    label_12 = QtWidgets.QLabel(gridLayoutWidget_3)
    label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    label_12.setObjectName("label_12")
    gridLayout_4.addWidget(label_12, 0, 0, 1, 1)
    label_13 = QtWidgets.QLabel(gridLayoutWidget_3)
    label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
    label_13.setObjectName("label_13")
    gridLayout_4.addWidget(label_13, 1, 0, 1, 1)
    comboBox = QtWidgets.QComboBox(gridLayoutWidget_3)
    comboBox.setCurrentText("")
    comboBox.setObjectName("comboBox")
    gridLayout_4.addWidget(comboBox, 0, 1, 1, 1)
    comboBox_2 = QtWidgets.QComboBox(gridLayoutWidget_3)
    comboBox_2.setCurrentText("")
    comboBox_2.setObjectName("comboBox_2")
    gridLayout_4.addWidget(comboBox_2, 1, 1, 1, 1)
    gridLayout_3.addLayout(gridLayout_4, 1, 0, 1, 2)

    _translate = QtCore.QCoreApplication.translate
    '''
    label.setText(_translate("MainWindow", "Point of Interest View"))
    label_2.setText(_translate("MainWindow", "Point of Interest A"))
    label_3.setText(_translate("MainWindow", "Point of Interest B"))
    label_4.setText(_translate("MainWindow", "Point of Interest C"))
    label_5.setText(_translate("MainWindow", "Point of Interest X"))
    pushButton.setText(_translate("MainWindow", "New"))
    '''
    groupBox_3.setTitle(_translate("MainWindow", "Point of Interest View"))
    pushButton_7.setText(_translate("MainWindow", "New"))

    pushButton_2.setText(_translate("MainWindow", "Delete"))
    pushButton_3.setText(_translate("MainWindow", "Save"))
    label_11.setText(_translate("MainWindow", "Point Of Interest Content Area"))
    label_6.setText(_translate("MainWindow", "Detail Point of Interest View"))
    label_12.setText(_translate("MainWindow", "Plugin"))
    label_13.setText(_translate("MainWindow", "Point of Interest Type"))
    
    return pointsOfInterestTab