from PyQt5 import QtCore, QtGui, QtWidgets, Qt
import os


class Tab5(QtWidgets.QWidget):
    def __init__(self, parent, main):
        QtWidgets.QWidget.__init__(self, parent)
        self.frame_4 = QtWidgets.QFrame(self)
        self.frame_4.setGeometry(QtCore.QRect(20, 10, 161, 550))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 40, 141, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 146, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 141, 17))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.frame_5 = QtWidgets.QFrame(self)
        self.frame_5.setGeometry(QtCore.QRect(199, 9, 581, 550))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(19, 49, 541, 461))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(180, 170, 171, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(200, 10, 171, 17))
        self.label_18.setObjectName("label_18")

        _translate = QtCore.QCoreApplication.translate

        self.label_14.setText(_translate("MainWindow", "Document View"))
        self.label_15.setText(_translate("MainWindow", "BEAT Documentation"))
        self.label_16.setText(_translate("MainWindow", "Plug In Structure"))
        self.label_17.setText(_translate("MainWindow", "Document Content Area"))
        self.label_18.setText(_translate("MainWindow", "Detailed Document View"))