from PyQt5 import QtCore, QtGui, QtWidgets
from src import pop
import r2pipe

class Tab2(QtWidgets.QWidget):
    def __init__(self, parent, main):
        QtWidgets.QWidget.__init__(self, parent)
        gridLayout = QtWidgets.QGridLayout(self)
        gridLayout.setObjectName("gridLayout")
        plugin_label = QtWidgets.QLabel(self)
        plugin_label.setAlignment(QtCore.Qt.AlignCenter)
        plugin_label.setObjectName("plugin_label")
        gridLayout.addWidget(plugin_label, 0, 0, 1, 1)
        plugin_comboBox = QtWidgets.QComboBox(self)
        plugin_comboBox.setMaxVisibleItems(10)
        plugin_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        plugin_comboBox.setObjectName("plugin_comboBox")
        plugin_comboBox.addItem("")
        plugin_comboBox.addItem("")
        plugin_comboBox.addItem("")
        gridLayout.addWidget(plugin_comboBox, 0, 1, 1, 1)
        static_anal_label = QtWidgets.QLabel(self)
        static_anal_label.setAlignment(QtCore.Qt.AlignCenter)
        static_anal_label.setObjectName("static_anal_label")
        gridLayout.addWidget(static_anal_label, 1, 0, 1, 1)
        static_run_button = QtWidgets.QPushButton(self)
        static_run_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        static_run_button.setObjectName("static_run_button")
        gridLayout.addWidget(static_run_button, 1, 1, 1, 1)
        dynamic_anal_label = QtWidgets.QLabel(self)
        dynamic_anal_label.setAlignment(QtCore.Qt.AlignCenter)
        dynamic_anal_label.setObjectName("dynamic_anal_label")
        gridLayout.addWidget(dynamic_anal_label, 1, 2, 1, 1)
        dynamic_run_button = QtWidgets.QPushButton(self)
        dynamic_run_button.setObjectName("dynamic_run_button")
        gridLayout.addWidget(dynamic_run_button, 1, 3, 1, 1)
        dynamic_stop_button = QtWidgets.QPushButton(self)
        dynamic_stop_button.setObjectName("dynamic_stop_button")
        gridLayout.addWidget(dynamic_stop_button, 1, 4, 1, 2)
        poi_label = QtWidgets.QLabel(self)
        poi_label.setAlignment(QtCore.Qt.AlignCenter)
        poi_label.setObjectName("poi_label")
        gridLayout.addWidget(poi_label, 2, 0, 1, 1)
        poi_comboBox = QtWidgets.QComboBox(self)
        poi_comboBox.setObjectName("poi_comboBox")
        poi_comboBox.addItem("")
        poi_comboBox.addItem("")
        poi_comboBox.addItem("")
        gridLayout.addWidget(poi_comboBox, 2, 1, 1, 1)
        gridLayout_6 = QtWidgets.QGridLayout()
        gridLayout_6.setObjectName("gridLayout_6")
        horizontalLayout = QtWidgets.QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        search_bar_lineEdit = QtWidgets.QLineEdit(self)
        search_bar_lineEdit.setFrame(True)
        search_bar_lineEdit.setObjectName("search_bar_lineEdit")
        search_bar_lineEdit.addAction(QtGui.QIcon("resources/search.png"), QtWidgets.QLineEdit.LeadingPosition)
        horizontalLayout.addWidget(search_bar_lineEdit)
        gridLayout_6.addLayout(horizontalLayout, 1, 1, 1, 1)
        scrollArea = QtWidgets.QScrollArea(self)
        scrollArea.setWidgetResizable(True)
        scrollArea.setObjectName("scrollArea")
        scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 243, 222))
        scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        gridLayout_4 = QtWidgets.QGridLayout(scrollAreaWidgetContents_2)
        gridLayout_4.setObjectName("gridLayout_4")
        checkBox_4 = QtWidgets.QCheckBox(scrollAreaWidgetContents_2)
        checkBox_4.setObjectName("checkBox_4")
        gridLayout_4.addWidget(checkBox_4, 4, 0, 1, 1)
        checkBox_6 = QtWidgets.QCheckBox(scrollAreaWidgetContents_2)
        checkBox_6.setObjectName("checkBox_6")
        gridLayout_4.addWidget(checkBox_6, 0, 0, 1, 1)
        checkBox_3 = QtWidgets.QCheckBox(scrollAreaWidgetContents_2)
        checkBox_3.setObjectName("checkBox_3")
        gridLayout_4.addWidget(checkBox_3, 5, 0, 1, 1)
        checkBox_2 = QtWidgets.QCheckBox(scrollAreaWidgetContents_2)
        checkBox_2.setObjectName("checkBox_2")
        gridLayout_4.addWidget(checkBox_2, 3, 0, 1, 1)
        checkBox_5 = QtWidgets.QCheckBox(scrollAreaWidgetContents_2)
        checkBox_5.setObjectName("checkBox_5")
        gridLayout_4.addWidget(checkBox_5, 2, 0, 1, 1)
        checkBox = QtWidgets.QCheckBox(scrollAreaWidgetContents_2)
        checkBox.setObjectName("checkBox")
        gridLayout_4.addWidget(checkBox, 1, 0, 1, 1)
        scrollArea.setWidget(scrollAreaWidgetContents_2)
        gridLayout_6.addWidget(scrollArea, 2, 1, 1, 1)
        poi_title_label = QtWidgets.QLabel(self)
        poi_title_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        poi_title_label.setAutoFillBackground(False)
        poi_title_label.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
                                           "background-color: rgb(0, 170, 255);")
        poi_title_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        poi_title_label.setObjectName("poi_title_label")
        gridLayout_6.addWidget(poi_title_label, 0, 1, 1, 1)
        gridLayout.addLayout(gridLayout_6, 3, 0, 2, 2)
        a_pushButton = QtWidgets.QPushButton(self)
        a_pushButton.setMaximumSize(QtCore.QSize(16, 20))
        a_pushButton.clicked.connect(self.openAnalysis)
        a_pushButton.setObjectName("a_pushButton")
        gridLayout.addWidget(a_pushButton, 3, 5, 1, 1)
        scrollArea_2 = QtWidgets.QScrollArea(self)
        scrollArea_2.setWidgetResizable(True)
        scrollArea_2.setObjectName("scrollArea_2")
        scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 373, 253))
        scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        gridLayout_2 = QtWidgets.QGridLayout(scrollAreaWidgetContents_3)
        gridLayout_2.setObjectName("gridLayout_2")
        poi_content_area_textEdit = QtWidgets.QTextEdit(scrollAreaWidgetContents_3)
        poi_content_area_textEdit.setObjectName("poi_content_area_textEdit")
        gridLayout_2.addWidget(poi_content_area_textEdit, 0, 0, 1, 1)
        c_pushButton = QtWidgets.QPushButton(scrollAreaWidgetContents_3)
        c_pushButton.setMaximumSize(QtCore.QSize(16, 20))
        c_pushButton.clicked.connect(self.openComment)
        c_pushButton.setObjectName("c_pushButton")
        gridLayout_2.addWidget(c_pushButton, 0, 1, 1, 1)
        terminal_window_lineEdit = QtWidgets.QLineEdit(scrollAreaWidgetContents_3)
        terminal_window_lineEdit.setObjectName("terminal_window_lineEdit")
        gridLayout_2.addWidget(terminal_window_lineEdit, 1, 0, 1, 1)
        scrollArea_2.setWidget(scrollAreaWidgetContents_3)
        gridLayout.addWidget(scrollArea_2, 4, 2, 1, 3)
        o_pushButton = QtWidgets.QPushButton(self)
        o_pushButton.setMaximumSize(QtCore.QSize(16, 20))
        o_pushButton.clicked.connect(self.openOutput)
        o_pushButton.setObjectName("o_pushButton")
        gridLayout.addWidget(o_pushButton, 4, 5, 1, 1)
        detailed_poi_view_label = QtWidgets.QLabel(self)
        detailed_poi_view_label.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
                                                   "background-color: rgb(0, 170, 255);")
        detailed_poi_view_label.setAlignment(QtCore.Qt.AlignCenter)
        detailed_poi_view_label.setObjectName("detailed_poi_view_label")
        gridLayout.addWidget(detailed_poi_view_label, 3, 2, 1, 3)
    
        _translate = QtCore.QCoreApplication.translate
    
        plugin_label.setText(_translate("MainWindow", "Plugin"))
        plugin_comboBox.setItemText(0, _translate("MainWindow", "Plugin A"))
        plugin_comboBox.setItemText(1, _translate("MainWindow", "Plugin B"))
        plugin_comboBox.setItemText(2, _translate("MainWindow", "Plugin C"))
        static_anal_label.setText(_translate("MainWindow", "Static Analysis"))
        static_run_button.setText(_translate("MainWindow", "Run"))
        dynamic_anal_label.setText(_translate("MainWindow", "Dynamic Analysis"))
        dynamic_run_button.setText(_translate("MainWindow", "Run"))
        dynamic_stop_button.setText(_translate("MainWindow", "Stop"))
        poi_label.setText(_translate("MainWindow", "Point of Interest"))
        poi_comboBox.setItemText(0, _translate("MainWindow", "DLL"))
        poi_comboBox.setItemText(1, _translate("MainWindow", "Structs"))
        poi_comboBox.setItemText(2, _translate("MainWindow", "Strings"))
        checkBox_4.setText(_translate("MainWindow", "Point of Interest E"))
        checkBox_6.setText(_translate("MainWindow", "Point of Interest A"))
        checkBox_3.setText(_translate("MainWindow", "Point of Interest X"))
        checkBox_2.setText(_translate("MainWindow", "Point of Interest D"))
        checkBox_5.setText(_translate("MainWindow", "Point of Interest C"))
        checkBox.setText(_translate("MainWindow", "Point of Interest B"))
        poi_title_label.setText(_translate("MainWindow",
                                                "<html><head/><body><p><span style=\" font-weight:600;\">Point of Interest View</span></p></body></html>"))
        a_pushButton.setText(_translate("MainWindow", "A"))
        c_pushButton.setText(_translate("MainWindow", "C"))
        o_pushButton.setText(_translate("MainWindow", "O"))
        detailed_poi_view_label.setText(_translate("MainWindow",
                                                    "<html><head/><body><p><span style=\" font-weight:600;\">Detailed Point of Interst View</span></p></body></html>"))


    def openComment(self):
        popUp = pop.commentDialog(self)
        text = popUp.exec_()
        print(text)

    def openAnalysis(self):
        popUp = pop.analysisResultDialog(self)
        text = popUp.exec_()
        print(text)

    def openOutput(self):
        popUp = pop.outputFieldDialog(self)
        text = popUp.exec_()
        print(text)

    def runDynamicAnalysis(self):
        r2 = r2pipe.open("./main.exe")

